name: CI  # The name of your workflow

on:  # Triggers for the workflow
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches: 
      - main
      - 'feature/**'

jobs:
  build:  # The build job
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:  # Steps to run in the build job
    - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

      # Publie les fichiers présents dans le dossier target dans un build artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: my-app-1.0
        path: target/*

      # Installe la commande docker sur l'agent
    - name: Install Docker
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
        
    # Build l'image Docker
    - name: Docker build
      run: |
        docker build .
