name: CI  # The name of your workflow

on:  # Triggers for the workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:  # The build job
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:  # Steps to run in the build job
    - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
